services:
  webapp:
    image: spring-webflux
    build:
      context: .
      dockerfile: Dockerfile
    container_name: naver-news
    env_file:
      - .env
    environment:
          DB_HOST: mysql
          REDIS_HOST: redis
          ELASTICSEARCH_HOST: elasticsearch
          LOGSTASH_HOST: logstash
    ports:
      - "3579:3579"
    restart: unless-stopped
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
    name: resources_local-network
