server:
  port: ${APP_PORT}

spring:
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: r2dbc:pool:mysql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}

app:
  duplicate:
    threshold: ${DUPLICATED_COUNT}

naver:
  openapi:
    url: ${NAVER_OPENAPI_URL}
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}
  search:
    display: ${NAVER_SEARCH_DISPLAY}
    start: ${NAVER_SEARCH_START}
    sort: ${NAVER_SEARCH_SORT}

slack:
  webhook:
    breaking: ${BREAKING_NEWS_WEBHOOK_URL}
    exclusive: ${EXCLUSIVE_NEWS_WEBHOOK_URL}
    develop: ${DEVELOP_WEBHOOK_URL}

logstash:
  host: ${LOGSTASH_HOST}
  tcp-port: ${LOGSTASH_TCP_PORT}

elk:
  active: ${ELK_ACTIVE}

chatgpt:
  api-key: ${CHATGPT_API_KEY}
  api-url: ${CHATGPT_API_URL}
  model: ${CHATGPT_MODEL}
  temperature: ${CHATGPT_TEMPERATURE}
  max-tokens: ${CHATGPT_MAX_TOKENS}
  summary-max-tokens: ${CHATGPT_SUMMARY_MAX_TOKENS}
